// CSX Fall Men 40+ IV 2026 - Official League Data (Auto-Synced from Capelli EZFacility)
const LEAGUE_INFO = {
    name: "CSX Fall Men 40+ IV 2026",
    division: "8 v 8 - Adult Soccer (Men's Over 40)",
    facility: "Capelli Sport Complex, Tinton Falls, NJ",
    ezfacility_url: "https://gaacomplextintonfalls.ezleagues.ezfacility.com/leagues/480009/CSX-Fall-Men-40-IV-2026.aspx"
};

const STANDINGS_DATA = [
    {
        "rank": 1,
        "team": "ELLAS",
        "gp": 3,
        "w": 3,
        "l": 0,
        "t": 0,
        "gf": 15,
        "ga": 4,
        "pts": 9,
        "gd": 11,
        "isClub": false
    },
    {
        "rank": 2,
        "team": "OCEAN ALUMNI FC",
        "gp": 3,
        "w": 2,
        "l": 1,
        "t": 0,
        "gf": 16,
        "ga": 7,
        "pts": 6,
        "gd": 9,
        "isClub": false
    },
    {
        "rank": 3,
        "team": "OUT OF SHAPE ALL STARS",
        "gp": 3,
        "w": 2,
        "l": 1,
        "t": 0,
        "gf": 14,
        "ga": 13,
        "pts": 6,
        "gd": 1,
        "isClub": false
    },
    {
        "rank": 4,
        "team": "FC JUVENTUS 40+",
        "gp": 3,
        "w": 2,
        "l": 1,
        "t": 0,
        "gf": 10,
        "ga": 13,
        "pts": 6,
        "gd": -3,
        "isClub": false
    },
    {
        "rank": 5,
        "team": "STRANGERS UNITED",
        "gp": 3,
        "w": 0,
        "l": 3,
        "t": 0,
        "gf": 4,
        "ga": 7,
        "pts": 0,
        "gd": -3,
        "isClub": true
    },
    {
        "rank": 6,
        "team": "CASUAL WRECKS",
        "gp": 3,
        "w": 0,
        "l": 3,
        "t": 0,
        "gf": 6,
        "ga": 21,
        "pts": 0,
        "gd": -15,
        "isClub": false
    }
];

const MATCHES_DATA = [
    {
        "id": 1,
        "date": "Thu, Sep 3",
        "time": "",
        "home": "STRANGERS UNITED",
        "away": "OUT OF SHAPE ALL STARS",
        "score": "2 - 3",
        "status": "Completed",
        "venue": "Wayside 4AB",
        "isClubMatch": true,
        "result": "L"
    },
    {
        "id": 2,
        "date": "Thu, Sep 3",
        "time": "",
        "home": "ELLAS",
        "away": "OCEAN ALUMNI FC",
        "score": "5 - 0",
        "status": "Completed",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Completed"
    },
    {
        "id": 3,
        "date": "Thu, Sep 3",
        "time": "",
        "home": "FC JUVENTUS 40+",
        "away": "CASUAL WRECKS",
        "score": "4 - 3",
        "status": "Completed",
        "venue": "Wayside 4CD",
        "isClubMatch": false,
        "result": "Completed"
    },
    {
        "id": 4,
        "date": "Thu, Sep 10",
        "time": "",
        "home": "CASUAL WRECKS",
        "away": "OCEAN ALUMNI FC",
        "score": "0 - 9",
        "status": "Completed",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Completed"
    },
    {
        "id": 5,
        "date": "Thu, Sep 10",
        "time": "",
        "home": "STRANGERS UNITED",
        "away": "ELLAS",
        "score": "1 - 2",
        "status": "Completed",
        "venue": "Wayside 4AB",
        "isClubMatch": true,
        "result": "L"
    },
    {
        "id": 6,
        "date": "Thu, Sep 10",
        "time": "",
        "home": "OUT OF SHAPE ALL STARS",
        "away": "FC JUVENTUS 40+",
        "score": "9 - 4",
        "status": "Completed",
        "venue": "Wayside 6AB",
        "isClubMatch": false,
        "result": "Completed"
    },
    {
        "id": 7,
        "date": "Thu, Sep 17",
        "time": "",
        "home": "CASUAL WRECKS",
        "away": "ELLAS",
        "score": "3 - 8",
        "status": "Completed",
        "venue": "Wayside 5AB",
        "isClubMatch": false,
        "result": "Completed"
    },
    {
        "id": 8,
        "date": "Thu, Sep 17",
        "time": "",
        "home": "OCEAN ALUMNI FC",
        "away": "OUT OF SHAPE ALL STARS",
        "score": "7 - 2",
        "status": "Completed",
        "venue": "Wayside 6AB",
        "isClubMatch": false,
        "result": "Completed"
    },
    {
        "id": 9,
        "date": "Thu, Sep 17",
        "time": "",
        "home": "STRANGERS UNITED",
        "away": "FC JUVENTUS 40+",
        "score": "1 - 2",
        "status": "Completed",
        "venue": "Wayside 6CD",
        "isClubMatch": true,
        "result": "L"
    },
    {
        "id": 10,
        "date": "Thu, Sep 24",
        "time": "8:00 PM",
        "home": "STRANGERS UNITED",
        "away": "CASUAL WRECKS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 4AB",
        "isClubMatch": true,
        "result": "Upcoming"
    },
    {
        "id": 11,
        "date": "Thu, Sep 24",
        "time": "8:00 PM",
        "home": "FC JUVENTUS 40+",
        "away": "OCEAN ALUMNI FC",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 12,
        "date": "Thu, Sep 24",
        "time": "9:00 PM",
        "home": "ELLAS",
        "away": "OUT OF SHAPE ALL STARS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 13,
        "date": "Thu, Oct 1",
        "time": "8:00 PM",
        "home": "CASUAL WRECKS",
        "away": "OUT OF SHAPE ALL STARS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 14,
        "date": "Thu, Oct 1",
        "time": "10:00 PM",
        "home": "OCEAN ALUMNI FC",
        "away": "STRANGERS UNITED",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 4CD",
        "isClubMatch": true,
        "result": "Upcoming"
    },
    {
        "id": 15,
        "date": "Thu, Oct 1",
        "time": "10:00 PM",
        "home": "FC JUVENTUS 40+",
        "away": "ELLAS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 16,
        "date": "Thu, Oct 8",
        "time": "8:00 PM",
        "home": "OCEAN ALUMNI FC",
        "away": "ELLAS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 17,
        "date": "Thu, Oct 8",
        "time": "8:00 PM",
        "home": "OUT OF SHAPE ALL STARS",
        "away": "STRANGERS UNITED",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 6CD",
        "isClubMatch": true,
        "result": "Upcoming"
    },
    {
        "id": 18,
        "date": "Thu, Oct 8",
        "time": "9:00 PM",
        "home": "CASUAL WRECKS",
        "away": "FC JUVENTUS 40+",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 19,
        "date": "Thu, Oct 15",
        "time": "9:00 PM",
        "home": "ELLAS",
        "away": "STRANGERS UNITED",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 4AB",
        "isClubMatch": true,
        "result": "Upcoming"
    },
    {
        "id": 20,
        "date": "Thu, Oct 15",
        "time": "9:00 PM",
        "home": "OCEAN ALUMNI FC",
        "away": "CASUAL WRECKS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 6CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 21,
        "date": "Thu, Oct 15",
        "time": "10:00 PM",
        "home": "OUT OF SHAPE ALL STARS",
        "away": "FC JUVENTUS 40+",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 22,
        "date": "Thu, Oct 22",
        "time": "9:00 PM",
        "home": "FC JUVENTUS 40+",
        "away": "STRANGERS UNITED",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 4CD",
        "isClubMatch": true,
        "result": "Upcoming"
    },
    {
        "id": 23,
        "date": "Thu, Oct 22",
        "time": "10:00 PM",
        "home": "OUT OF SHAPE ALL STARS",
        "away": "OCEAN ALUMNI FC",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 4CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 24,
        "date": "Thu, Oct 22",
        "time": "10:00 PM",
        "home": "ELLAS",
        "away": "CASUAL WRECKS",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 25,
        "date": "Thu, Oct 29",
        "time": "8:00 PM",
        "home": "1st Place",
        "away": "4th Place",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 26,
        "date": "Thu, Oct 29",
        "time": "9:00 PM",
        "home": "2nd Place",
        "away": "3rd Place",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 27,
        "date": "Thu, Oct 29",
        "time": "10:00 PM",
        "home": "5th Place",
        "away": "6th Place",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    },
    {
        "id": 28,
        "date": "Thu, Nov 5",
        "time": "10:00 PM",
        "home": "Winner 1st vs 4th",
        "away": "Winner 2nd vs 3rd",
        "score": "vs",
        "status": "Upcoming",
        "venue": "Wayside 5CD",
        "isClubMatch": false,
        "result": "Upcoming"
    }
];
